#include <esp_log.h>
#include "LogUtils.h"

#define PMW_TAG_PREFIX "PMW_"

#define PMW_CN_BOOT "Boot"
const char* COMPONENT_NAME_BOOT = PMW_CN_BOOT;
const char* COMPONENT_TAG_BOOT = PMW_TAG_PREFIX PMW_CN_BOOT;

#define PMW_CN_BOOT_GUI "Boot_GUI"
const char* COMPONENT_NAME_BOOT_GUI = PMW_CN_BOOT_GUI;
const char* COMPONENT_TAG_BOOT_GUI = PMW_TAG_PREFIX PMW_CN_BOOT_GUI;

#define PMW_CN_GUI "GUI"
const char* COMPONENT_NAME_GUI = PMW_CN_GUI;
const char* COMPONENT_TAG_GUI = PMW_TAG_PREFIX PMW_CN_GUI;

#define PMW_CN_SETTINGS_STORAGE "Settings_Storage"
const char* COMPONENT_NAME_SETTINGS_STORAGE = PMW_CN_SETTINGS_STORAGE;
const char* COMPONENT_TAG_SETTINGS_STORAGE = PMW_TAG_PREFIX PMW_CN_SETTINGS_STORAGE;

#define PMW_CN_STORAGE_PARTITION_MANAGER "Storage_Partition_Manager"
const char* COMPONENT_NAME_STORAGE_PARTITION_MANAGER = PMW_CN_STORAGE_PARTITION_MANAGER;
const char* COMPONENT_TAG_STORAGE_PARTITION_MANAGER = PMW_TAG_PREFIX PMW_CN_STORAGE_PARTITION_MANAGER;

void setComponentsDefaultLogLevel()
{
    esp_log_level_set(COMPONENT_TAG_BOOT, static_cast<esp_log_level_t>(CONFIG_LOG_DEFAULT_LEVEL_BOOT));
}
